# Generated by Django 5.2.12 on 2026-03-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('aceita_termos', models.BooleanField(default=False)),
                ('aceita_uso_imagem', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_apartamento', models.CharField(max_length=200)),
                ('nome_rua', models.CharField(max_length=200)),
                ('endereco_completo', models.CharField(max_length=255)),
                ('imagem_apartamento', models.ImageField(blank=True, null=True, upload_to='apartamentos/')),
                ('aviso_importante', models.TextField(blank=True, help_text='Texto do card de avisos importantes no topo da página aprovada.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['nome_apartamento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hospede', models.CharField(choices=[('titular', 'Titular'), ('acompanhante', 'Acompanhante')], default='acompanhante', max_length=20)),
                ('nome_completo', models.CharField(max_length=200)),
                ('estrangeiro', models.BooleanField(default=False)),
                ('cpf', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('rua', models.CharField(blank=True, max_length=200)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('foto_verso', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('selfie_rosto', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedes', to='checkin.checkin')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemGuiaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(choices=[('estadia', 'Sua Estadia'), ('imovel', 'Guia do Imóvel'), ('area', 'Guia da Área')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_conteudo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem')], default='texto', max_length=20)),
                ('conteudo', models.TextField(blank=True, help_text='Use este campo quando o item for do tipo texto.')),
                ('imagem', models.ImageField(blank=True, help_text='Use este campo quando o item for do tipo imagem.', null=True, upload_to='guias/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_guia', to='checkin.imovel')),
            ],
            options={
                'verbose_name': 'Item da guia do imóvel',
                'verbose_name_plural': 'Itens das guias do imóvel',
                'ordering': ['guia', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReservaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=50, unique=True)),
                ('nome_imovel', models.CharField(help_text='Nome vindo da reserva/importação. Pode ser igual ao nome do imóvel.', max_length=200)),
                ('endereco', models.CharField(help_text='Endereço vindo da reserva/importação. Pode ser igual ao endereço do imóvel.', max_length=255)),
                ('data_checkin', models.DateTimeField()),
                ('data_checkout', models.DateTimeField()),
                ('quantidade_hospedes', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='checkin.imovel')),
            ],
            options={
                'verbose_name': 'Reserva do imóvel',
                'verbose_name_plural': 'Reservas dos imóveis',
                'ordering': ['-data_checkin', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='checkin.reservaimovel'),
        ),
    ]
