# Generated by Django 5.2.12 on 2026-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemguiaimovel',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemguiaimovel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='guias/'),
        ),
        migrations.AlterField(
            model_name='reservaimovel',
            name='endereco',
            field=models.CharField(blank=True, help_text='Opcional. Se ficar vazio, usa o endereço do imóvel.', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservaimovel',
            name='nome_imovel',
            field=models.CharField(blank=True, help_text='Opcional. Se ficar vazio, usa o nome do imóvel.', max_length=200),
        ),
    ]
