# Generated by Django 5.2.12 on 2026-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_itemguiaimovel_conteudo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='cpf',
        ),
        migrations.AddField(
            model_name='hospede',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF para brasileiros ou passaporte/RNE/outro documento para estrangeiros.', max_length=50),
        ),
    ]
